[project]
name = "ai-agent-semantic-router"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-search-results>=2.4.2",
    "groq>=0.37.1",
    "langchain>=1.3.10",
    "langchain-community>=0.4.2",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.6",
    "langgraph-checkpoint-sqlite>=3.1.0",
    "python-dotenv>=1.2.2",
    "semantic-router[local]>=0.1.15",
    "wikipedia>=1.4.0",
    "yfinance>=1.4.1",
    "torch>=2.12.1",
    "transformers>=5.12.1",
    "tokenizers>=0.22.0,<=0.23.0",
    "ipython>=9.14.1",
    "grandalf>=0.8",
]
